import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "./auth/ReduxProvider";
import GetUserLayout from "./Layouts/GetUserLayout";
import QueryLayout from "./Layouts/QueryLayout";
import NavLayout from "./Layouts/NavLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cryptoboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[var(--black20)] text-[var(--black100)] flex flex-col`}
      >
        <ReduxProvider>
          <GetUserLayout>
            <QueryLayout>
              <NavLayout>{children}</NavLayout>
            </QueryLayout>
          </GetUserLayout>
        </ReduxProvider>
      </body>
    </html>
  );
}
